# services:

#   web:
  #   build: .
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true
  #     redis:
  #       condition: service_started

  # redis:
  #   image: redis
